-- Adding CTEs to simplify the query and improve readability and potential performance
WITH
account_info AS (
    SELECT
        ac.account_id,
        ac.name AS account_name,
        ac.official_name AS account_official_name,
        COALESCE(ac.mask, 0) AS account_mask,
        COALESCE(ac.days_available, 0) AS account_days_available,
        ac.type AS account_type,
        ac.subtype AS account_subtype,
        COALESCE(ac.current, 0) AS account_current_balance,
        COALESCE(ac.available, 0) AS account_limit_available,
        COALESCE(ac.limit, 0) AS account_limit,
        COALESCE(ac.iso_currency_code, ac.unofficial_currency_code) AS account_iso_currency_code,
        COALESCE(ac.margin_loan_amount, 0) AS account_margin_loan_amount,
        MAX(IF(ac.type IN ('depository', 'investment'), 1, 0)) AS account_is_asset,
        MAX(IF(ac.type IN ('credit', 'loan'), 1, 0)) AS account_is_liability
    FROM
        asset_account ac
    GROUP BY
        ac.account_id, ac.name, ac.official_name, ac.mask, ac.days_available,
        ac.type, ac.subtype, ac.current, ac.available, ac.limit, ac.iso_currency_code,
        ac.unofficial_currency_code, ac.margin_loan_amount
),
transaction_info AS (
    SELECT
        pt.transaction_id,
        COALESCE(pt.amount * -1, 0) AS transaction_amount,
        MAX(IF(COALESCE(pt.amount * -1, 0) > 0, 1, 0)) AS is_transaction_inflow,
        MAX(IF(COALESCE(pt.amount * -1, 0) < 0, 1, 0)) AS is_transaction_outflow,
        ABS(pt.amount) AS transaction_amount_absolute,
        pt.authorized_date AS transaction_authorized_date,
        DAY(pt.authorized_date) AS transaction_authorized_day,
        pt.date AS transaction_date,
        COALESCE(pt.iso_currency_code, pt.unofficial_currency_code) AS iso_currency_code,
        pt.logo_url AS transaction_logo_url,
        pt.merchant_entity_id AS merchant_entity_id,
        pt.merchant_name AS merchant_name,
        pt.name AS transaction_name,
        pt.payment_channel AS payment_channel,
        COALESCE(pt.pending, 0) AS transaction_pending,
        pt.pending_transaction_id AS pending_transaction_id,
        pt.transaction_code AS transaction_code,
        pt.transaction_type AS transaction_type,
        pt.unofficial_currency_code AS unofficial_currency_code,
        pt.personal_finance_category_confidence_level AS personal_finance_category_confidence_level,
        pt.personal_finance_category_detailed AS personal_finance_category_detailed,
        pt.personal_finance_category_primary AS personal_finance_category_primary,
        pt.personal_finance_category_icon_url AS personal_finance_category_icon_url,
        pt.location_address AS location_address,
        pt.location_city AS location_city,
        pt.location_region AS location_region,
        pt.location_postal_code AS location_postal_code,
        pt.location_country AS location_country,
        COALESCE(pt.location_lat, 0) AS location_lat,
        COALESCE(pt.location_lon, 0) AS location_lon,
        pt.location_store_number AS location_store_number,
        pt.payment_meta_reference_number AS payment_meta_reference_number,
        pt.payment_meta_ppd_id AS payment_meta_ppd_id,
        pt.payment_meta_payee AS payment_meta_payee,
        pt.payment_meta_by_order_of AS payment_meta_by_order_of,
        pt.payment_meta_payer AS payment_meta_payer,
        pt.payment_meta_payment_method AS payment_meta_payment_method,
        pt.payment_meta_payment_processor AS payment_meta_payment_processor,
        pt.payment_meta_reason AS payment_meta_reason,
        pt.website AS merchant_website,
        pt.check_number AS check_number,
        DAYOFWEEK(pt.date) AS transaction_day_of_week,
        MONTH(pt.date) AS transaction_month,
        YEAR(pt.date) AS transaction_year,
        MAX(IF(DAYOFWEEK(pt.date) IN (1, 7), 1, 0)) AS is_weekend_transaction,
        cat.category_group AS transaction_category_group,
        cat.hierarchy_level1 AS transaction_hierarchy_level1,
        cat.hierarchy_level2 AS transaction_hierarchy_level2,
        cat.hierarchy_level3 AS transaction_hierarchy_level3
    FROM
        plaid_transactions pt
    LEFT JOIN
        plaid.categories cat ON pt.category_id = cat.category_id
    GROUP BY
        pt.transaction_id, pt.amount, pt.authorized_date, pt.date, pt.iso_currency_code,
        pt.unofficial_currency_code, pt.logo_url, pt.merchant_entity_id, pt.merchant_name,
        pt.name, pt.payment_channel, pt.pending, pt.pending_transaction_id, pt.transaction_code,
        pt.transaction_type, pt.personal_finance_category_confidence_level, pt.personal_finance_category_detailed,
        pt.personal_finance_category_primary, pt.personal_finance_category_icon_url, pt.location_address,
        pt.location_city, pt.location_region, pt.location_postal_code, pt.location_country, pt.location_lat,
        pt.location_lon, pt.location_store_number, pt.payment_meta_reference_number, pt.payment_meta_ppd_id,
        pt.payment_meta_payee, pt.payment_meta_by_order_of, pt.payment_meta_payer, pt.payment_meta_payment_method,
        pt.payment_meta_payment_processor, pt.payment_meta_reason, pt.website, pt.check_number, cat.category_group,
        cat.hierarchy_level1, cat.hierarchy_level2, cat.hierarchy_level3
)

SELECT
    bc.item_id AS bank_id,
    bc.institution_name AS bank_name,
    ac.account_id,
    ac.account_name,
    ac.account_official_name,
    ac.account_mask,
    ac.account_days_available,
    ac.account_type,
    ac.account_subtype,
    ac.account_current_balance,
    ac.account_limit_available,
    ac.account_limit,
    ac.account_iso_currency_code,
    ac.account_margin_loan_amount,
    ac.account_is_asset,
    ac.account_is_liability,
    MAX(IF(plca.apr_type = 'purchase_apr', plca.apr_percentage, 0)) AS account_purchase_annual_interest_rate,
    MAX(IF(plca.apr_type = 'cash_apr', plca.apr_percentage, 0)) AS account_cash_annual_interest_rate,
    MAX(IF(plca.apr_type = 'balance_transfer_apr', plca.apr_percentage, 0)) AS account_balance_transfer_annual_interest_rate,
    tr.transaction_id,
    tr.transaction_amount,
    tr.is_transaction_inflow,
    tr.is_transaction_outflow,
    tr.transaction_amount_absolute,
    tr.transaction_authorized_date,
    tr.transaction_authorized_day,
    tr.transaction_date,
    tr.iso_currency_code,
    tr.transaction_logo_url,
    tr.merchant_entity_id,
    tr.merchant_name,
    tr.transaction_name,
    tr.payment_channel,
    tr.transaction_pending,
    tr.pending_transaction_id,
    tr.transaction_code,
    tr.transaction_type,
    tr.unofficial_currency_code,
    tr.personal_finance_category_confidence_level,
    tr.personal_finance_category_detailed,
    tr.personal_finance_category_primary,
    tr.personal_finance_category_icon_url,
    tr.location_address,
    tr.location_city,
    tr.location_region,
    tr.location_postal_code,
    tr.location_country,
    tr.location_lat,
    tr.location_lon,
    tr.location_store_number,
    tr.payment_meta_reference_number,
    tr.payment_meta_ppd_id,
    tr.payment_meta_payee,
    tr.payment_meta_by_order_of,
    tr.payment_meta_payer,
    tr.payment_meta_payment_method,
    tr.payment_meta_payment_processor,
    tr.payment_meta_reason,
    tr.merchant_website,
    tr.check_number,
    tr.transaction_day_of_week,
    tr.transaction_month,
    tr.transaction_year,
    tr.is_weekend_transaction,
    tr.transaction_category_group,
    tr.transaction_hierarchy_level1,
    tr.transaction_hierarchy_level2,
    tr.transaction_hierarchy_level3
FROM
    asset_report re
INNER JOIN
    asset_item bc ON bc.asset_report_id = re.asset_report_id
INNER JOIN
    account_info ac ON re.asset_report_id = ac.asset_report_id AND bc.item_id = ac.item_id
LEFT JOIN
    plaid_liabilities_credit_apr plca ON ac.account_id = plca.account_id
LEFT JOIN
    asset_transaction tr ON re.asset_report_id = tr.asset_report_id AND ac.account_id = tr.account_id
INNER JOIN
    transaction_info pt ON ac.account_id = pt.account_id AND tr.transaction_id = pt.transaction_id
GROUP BY
    bc.item_id, ac.account_id, tr.transaction_id,
    ac.account_name, ac.account_official_name, ac.account_mask, ac.account_days_available, ac.account_type,
    ac.account_subtype, ac.account_current_balance, ac.account_limit_available, ac.account_limit,
    ac.account_iso_currency_code, ac.account_margin_loan_amount, ac.account_is_asset, ac.account_is_liability,
    tr.transaction_amount, tr.is_transaction_inflow, tr.is_transaction_outflow, tr.transaction_amount_absolute,
    tr.transaction_authorized_date, tr.transaction_authorized_day, tr.transaction_date, tr.iso_currency_code,
    tr.transaction_logo_url, tr.merchant_entity_id, tr.merchant_name, tr.transaction_name, tr.payment_channel,
    tr.transaction_pending, tr.pending_transaction_id, tr.transaction_code, tr.transaction_type,
    tr.unofficial_currency_code, tr.personal_finance_category_confidence_level, tr.personal_finance_category_detailed,
    tr.personal_finance_category_primary, tr.personal_finance_category_icon_url, tr.location_address,
    tr.location_city, tr.location_region, tr.location_postal_code, tr.location_country, tr.location_lat,
    tr.location_lon, tr.location_store_number, tr.payment_meta_reference_number, tr.payment_meta_ppd_id,
    tr.payment_meta_payee, tr.payment_meta_by_order_of, tr.payment_meta_payer, tr.payment_meta_payment_method,
    tr.payment_meta_payment_processor, tr.payment_meta_reason, tr.merchant_website, tr.check_number, tr.transaction_day_of_week,
    tr.transaction_month, tr.transaction_year, tr.is_weekend_transaction, tr.transaction_category_group,
    tr.transaction_hierarchy_level1, tr.transaction_hierarchy_level2, tr.transaction_hierarchy_level3
