SELECT
    bc.item_id AS bank_id,
    bc.institution_name AS bank_name,
    ac.account_id,
    ac.name AS account_name,
    ac.official_name AS account_official_name,
    COALESCE(ac.mask, 0) AS account_mask,
    COALESCE(ac.days_available, 0) AS account_days_available,
    ac.type AS account_type,
    ac.subtype AS account_subtype,
    COALESCE(ac.current, 0) AS account_current_balance,
    COALESCE(ac.available, 0) AS account_limit_available,
    COALESCE(ac.limit, 0) AS account_limit,
    COALESCE(ac.iso_currency_code, ac.unofficial_currency_code) AS account_iso_currency_code,
    COALESCE(ac.margin_loan_amount, 0) AS account_margin_loan_amount,
    MAX(IF(ac.type IN ('depository', 'investment'), 1, 0)) AS account_is_asset,
    MAX(IF(ac.type IN ('credit', 'loan'), 1, 0)) AS account_is_liability,
    MAX(IF(plca.apr_type = 'purchase_apr', plca.apr_percentage, 0)) AS account_purchase_annual_interest_rate,
    MAX(IF(plca.apr_type = 'cash_apr', plca.apr_percentage, 0)) AS account_cash_annual_interest_rate,
    MAX(IF(plca.apr_type = 'balance_transfer_apr', plca.apr_percentage, 0)) AS account_balance_transfer_annual_interest_rate,
    tr.transaction_id,
    COALESCE(pt.amount * -1, 0) AS transaction_amount,
    MAX(IF(COALESCE(pt.amount * -1, 0) > 0, 1, 0)) AS is_transaction_inflow,
    MAX(IF(COALESCE(pt.amount * -1, 0) < 0, 1, 0)) AS is_transaction_outflow,
    ABS(pt.amount) AS transaction_amount_absolute,
    pt.authorized_date AS transaction_authorized_date,
    DAY(pt.authorized_date) AS transaction_authorized_day,
    pt.date AS transaction_date,
    COALESCE(pt.iso_currency_code, pt.unofficial_currency_code) AS iso_currency_code,
    pt.logo_url AS transaction_logo_url,
    pt.merchant_entity_id AS merchant_entity_id,
    pt.merchant_name AS merchant_name,
    pt.name AS transaction_name,
    pt.payment_channel AS payment_channel,
    COALESCE(pt.pending, 0) AS transaction_pending,
    pt.pending_transaction_id AS pending_transaction_id,
    pt.transaction_code AS transaction_code,
    pt.transaction_type AS transaction_type,
    pt.unofficial_currency_code AS unofficial_currency_code,
    pt.personal_finance_category_confidence_level AS personal_finance_category_confidence_level,
    pt.personal_finance_category_detailed AS personal_finance_category_detailed,
    pt.personal_finance_category_primary AS personal_finance_category_primary,
    pt.personal_finance_category_icon_url AS personal_finance_category_icon_url,
    pt.location_address AS location_address,
    pt.location_city AS location_city,
    pt.location_region AS location_region,
    pt.location_postal_code AS location_postal_code,
    pt.location_country AS location_country,
    COALESCE(pt.location_lat, 0) AS location_lat,
    COALESCE(pt.location_lon, 0) AS location_lon,
    pt.location_store_number AS location_store_number,
    pt.payment_meta_reference_number AS payment_meta_reference_number,
    pt.payment_meta_ppd_id AS payment_meta_ppd_id,
    pt.payment_meta_payee AS payment_meta_payee,
    pt.payment_meta_by_order_of AS payment_meta_by_order_of,
    pt.payment_meta_payer AS payment_meta_payer,
    pt.payment_meta_payment_method AS payment_meta_payment_method,
    pt.payment_meta_payment_processor AS payment_meta_payment_processor,
    pt.payment_meta_reason AS payment_meta_reason,
    pt.website AS merchant_website,
    pt.check_number AS check_number,
    DAYOFWEEK(tr.date) AS transaction_day_of_week,
    MONTH(tr.date) AS transaction_month,
    YEAR(tr.date) AS transaction_year,
    MAX(IF(DAYOFWEEK(tr.date) IN (1, 7), 1, 0)) AS is_weekend_transaction,
    cat.category_group AS transaction_category_group,
    cat.hierarchy_level1 AS transaction_hierarchy_level1,
    cat.hierarchy_level2 AS transaction_hierarchy_level2,
    cat.hierarchy_level3 AS transaction_hierarchy_level3
FROM asset_report re
    INNER JOIN asset_item bc ON bc.asset_report_id = re.asset_report_id
    INNER JOIN asset_account ac ON re.asset_report_id = ac.asset_report_id AND bc.item_id = ac.item_id
    LEFT JOIN plaid_liabilities_credit_apr plca ON ac.account_id = plca.account_id
    LEFT JOIN asset_transaction tr ON re.asset_report_id = tr.asset_report_id AND ac.account_id = tr.account_id
    LEFT JOIN plaid_transactions pt ON ac.account_id = pt.account_id AND tr.transaction_id = pt.transaction_id
    LEFT JOIN plaid.categories cat ON pt.category_id = cat.category_id
GROUP BY
    bc.item_id, ac.account_id, tr.transaction_id,
    ac.name, ac.official_name, ac.mask, ac.days_available, ac.type, ac.subtype, ac.current, ac.available, ac.limit,
    ac.iso_currency_code, ac.unofficial_currency_code, ac.margin_loan_amount,
    tr.original_description, tr.date, pt.authorized_date, tr.amount, tr.transaction_id, pt.amount, pt.iso_currency_code,
    pt.unofficial_currency_code, pt.logo_url, pt.merchant_entity_id, pt.merchant_name, pt.name, pt.payment_channel,
    pt.pending, pt.pending_transaction_id, pt.transaction_code, pt.transaction_type,
    pt.personal_finance_category_confidence_level, pt.personal_finance_category_detailed,
    pt.personal_finance_category_primary, pt.personal_finance_category_icon_url, pt.location_address,
    pt.location_city, pt.location_region, pt.location_postal_code, pt.location_country, pt.location_lat,
    pt.location_lon, pt.location_store_number, pt.payment_meta_reference_number, pt.payment_meta_ppd_id,
    pt.payment_meta_payee, pt.payment_meta_by_order_of, pt.payment_meta_payer, pt.payment_meta_payment_method,
    pt.payment_meta_payment_processor, pt.payment_meta_reason, pt.website, pt.check_number, cat.category_group,
    cat.hierarchy_level1, cat.hierarchy_level2, cat.hierarchy_level3;
